### Numpy operations

In [1]:
import numpy as np

In [2]:
a = np.arange(5,15)
b = np.arange(25,35)

In [3]:
print(a)
print(b)

[ 5  6  7  8  9 10 11 12 13 14]
[25 26 27 28 29 30 31 32 33 34]


In [4]:
sum = a+b
print(sum)

[30 32 34 36 38 40 42 44 46 48]


In [5]:
sub = a-b
print(sub)

[-20 -20 -20 -20 -20 -20 -20 -20 -20 -20]


In [6]:
mul = a*b
print(mul)

[125 156 189 224 261 300 341 384 429 476]


In [7]:
div = a/b
print(div)

[0.2        0.23076923 0.25925926 0.28571429 0.31034483 0.33333333
 0.35483871 0.375      0.39393939 0.41176471]


In [8]:
print(a.sum(axis=0))

95


In [9]:
c = np.array([a,b])

In [10]:
print( c.sum(axis=0) )

[30 32 34 36 38 40 42 44 46 48]


In [11]:
print(c.sum(axis=1))

[ 95 295]


In [12]:
print( c*2 )

[[10 12 14 16 18 20 22 24 26 28]
 [50 52 54 56 58 60 62 64 66 68]]


In [13]:
print(c.min())

5


In [14]:
print(c.min(axis=0))

[ 5  6  7  8  9 10 11 12 13 14]


In [15]:
print(c.min(axis=1))

[ 5 25]


In [16]:
print(c.mean())

19.5


In [17]:
print(c.mean(axis=1))

[ 9.5 29.5]


In [18]:
print(c.prod(axis=0))

[125 156 189 224 261 300 341 384 429 476]


In [19]:
print(c.std(axis=1))

[2.87228132 2.87228132]


In [20]:
print(c[0, 1])

6


In [21]:
print(c[1:2])

[[25 26 27 28 29 30 31 32 33 34]]


In [22]:
print(c[0:2, 0:5])

[[ 5  6  7  8  9]
 [25 26 27 28 29]]


In [33]:
arr = np.array(
    [np.arange(1,11),np.arange(11,21),np.arange(21,31),np.arange(31,41)]
)

print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


### Reverse the array

In [34]:
print(np.flip(arr))

[[40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]


### transpose the array

In [28]:
print(np.transpose(arr))

[[ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]
 [ 4 14 24 34]
 [ 5 15 25 35]
 [ 6 16 26 36]
 [ 7 17 27 37]
 [ 8 18 28 38]
 [ 9 19 29 39]
 [10 20 30 40]]


In [32]:
print(arr.reshape((8,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


### flattening multidimensional arrays

In [41]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [36]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
a2 = x.ravel()
a2[3] = 98
print(x)  # Original array
print(a2)  # New array

[[ 1  2  3 98]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3 98  5  6  7  8  9 10 11 12]
