### import numpy

In [1]:
import numpy as np

In [2]:
l = [ 1,2,3 , 4,5,6 , 8,9,10 ]

### create the 1-D array

In [3]:
array_1 = np.array(l)

In [4]:
array_1

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

### check the dimension

In [5]:
array_1.ndim

1

In [6]:
array_1.shape

(9,)

### accessing the elements using the indexing

In [7]:
for i in range(len(array_1)):
    print(array_1[i])

1
2
3
4
5
6
8
9
10


### modify the array

In [8]:
array_1[5]=100

In [9]:
array_1

array([  1,   2,   3,   4,   5, 100,   8,   9,  10])

In [10]:
print(array_1[3:7])

[  4   5 100   8]


### create the 2-D array

In [11]:
l = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [12]:
array_2 = np.array(l)
print(array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### accessing the elements using the indexing

In [31]:
array_2[0]

array([1, 2, 3])

In [14]:
for i in range( 0,len(array_2) ):
    
    for j in range(0,len(array_2[i])):
        
        print(array_2[i,j])
        

1
2
3
4
5
6
7
8
9


### Array attributes

In [15]:
print(array_2.ndim)

2


In [16]:
print(array_2.shape)

(3, 3)


In [17]:
print(array_2.size)

9


In [18]:
print(array_2.dtype)

int32


# How to create a basic array

### zero array

In [19]:
zeros_1_d = np.zeros(5)
print(zeros_1_d)

print("**************")

zeros_2_d = np.zeros( (4,3) )
print(zeros_2_d)

[0. 0. 0. 0. 0.]
**************
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### ones array

In [20]:
ones_1_d = np.ones(5)
print(ones_1_d)

print("**************")

ones_2_d = np.ones( (4,3) )
print(ones_2_d)

[1. 1. 1. 1. 1.]
**************
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Create an empty array 

In [21]:
empty = np.empty(2) 
print(empty)

[3.00671108e-197 5.02609341e-114]


### create the array with the range of elements

In [22]:
array = np.arange(5)
print(array)

[0 1 2 3 4]


In [23]:
array = np.arange( 10,21 )
print(array)

[10 11 12 13 14 15 16 17 18 19 20]


In [24]:
array = np.arange( 10.00 ,51,5)
print(array)

[10. 15. 20. 25. 30. 35. 40. 45. 50.]


### creating the array with linespace

In [25]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.arange(20,31,dtype=np.float64)

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30.])