In [1]:
import numpy as np

### Adding, removing, and sorting elements

In [2]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(arr)

[2 1 5 3 7 4 6 8]


In [3]:
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 4 5 6 7 8]


In [4]:
arr = np.array(
    [
        [5,8,1,4,9],
        [2,7,6,3,0]
    ]
)

### sort along the columns

In [5]:
print(np.sort(arr,axis=0))

[[2 7 1 3 0]
 [5 8 6 4 9]]


### sort along the row

In [6]:
np.sort(arr,axis=1)

array([[1, 4, 5, 8, 9],
       [0, 2, 3, 6, 7]])

# concatination of arrays

In [7]:
a = np.arange(3,9)
b = np.arange(13,19)
c = np.arange(23,29)

In [8]:
combined_arr = np.concatenate( (a,b,c) )
print(combined_arr)

[ 3  4  5  6  7  8 13 14 15 16 17 18 23 24 25 26 27 28]


In [9]:
a = np.array(
    [
        np.arange(3,9),
        np.arange(33,39),
        np.arange(43,49)
    ]
)

b = b.reshape(1,6)

c = np.array([c]) 

print(a)
print(b)
print(c)

[[ 3  4  5  6  7  8]
 [33 34 35 36 37 38]
 [43 44 45 46 47 48]]
[[13 14 15 16 17 18]]
[[23 24 25 26 27 28]]


In [10]:
combined_arr = np.concatenate( (a,b,c)  ,axis=0)
print(combined_arr)

[[ 3  4  5  6  7  8]
 [33 34 35 36 37 38]
 [43 44 45 46 47 48]
 [13 14 15 16 17 18]
 [23 24 25 26 27 28]]


### 3-D array

In [11]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]]
                        )

In [12]:
print(array_example.ndim)
print(array_example.shape)
print(array_example.size)

3
(3, 2, 4)
24


### reshape the array

In [13]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [14]:
b = a.reshape(3, 3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Indexing and slicing

In [15]:
data = np.arange(1,16)

print(data)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [16]:
print(data[5:])

[ 6  7  8  9 10 11 12 13 14 15]


In [17]:
print(data[5:10])

[ 6  7  8  9 10]


In [18]:
print(data[:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
print(data[-10:])

[ 6  7  8  9 10 11 12 13 14 15]


### Applying the conditions

In [20]:
data[ data<10 ]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [22]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print( a[a<5] ) 

[1 2 3 4]


In [24]:
greatertahn_5 = (a>5)

print(a[greatertahn_5])

[ 6  7  8  9 10 11 12]


In [25]:
divisible_by_2 = a[ a%2 == 0 ]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [26]:
c = a[ (a > 2) & (a < 11) ]
print(c)

[ 3  4  5  6  7  8  9 10]


In [27]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
