In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
sentences = [
    "The glass of juice",
    "The glass of milk",
    "I like to play cricket",
    "Do you have pen",
    "you are so funny man!",
    "ilove you",
    "The baby was fresh like a daisy",
    "Her smile was like sunshine on a rainy day",
    'When we say something is as dark as coal we are using the known darkness of coal to emphasize how dark the night is'
]

In [3]:
sentences

['The glass of juice',
 'The glass of milk',
 'I like to play cricket',
 'Do you have pen',
 'you are so funny man!',
 'ilove you',
 'The baby was fresh like a daisy',
 'Her smile was like sunshine on a rainy day',
 'When we say something is as dark as coal we are using the known darkness of coal to emphasize how dark the night is']

In [4]:
import nltk
import re

# remove the stop words
from nltk.corpus import stopwords

# reduce the words to its root word
from nltk.stem.porter import PorterStemmer

In [5]:
ps = PorterStemmer()

In [6]:
ps.stem(sentences[0])

'the glass of juic'

In [7]:
 stop_words =  set( stopwords.words('english') )

In [8]:
def prprocessing( sent ) :
    
     # take only the words
    sent = re.sub( '[^a-zA-Z]' , ' ' , sent )
    
    sent = sent.lower()

    sent = sent.split()

    sent = [ ps.stem(word) for word in sent if word not in stop_words ]

     # join the words to form the sentence
    sent = ' '.join(sent)
    
    return sent

In [9]:
stemed_sentences= [ prprocessing(sentences[i]) for i in range( 0 , len(sentences) ) ]

In [10]:
stemed_sentences

['glass juic',
 'glass milk',
 'like play cricket',
 'pen',
 'funni man',
 'ilov',
 'babi fresh like daisi',
 'smile like sunshin raini day',
 'say someth dark coal use known dark coal emphas dark night']

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
encoder = OneHotEncoder(sparse_output=False , dtype=np.int32)

In [13]:
def transform(sent):
    sent = sent.split()

    sent = np.array( sent ).reshape(-1,1)

    one_hot_data = encoder.fit_transform(sent)
    
    return one_hot_data

In [14]:
transformed_data = [ transform(sent) for sent in stemed_sentences ]

In [15]:
for i in range(len(transformed_data)):
    print(transformed_data[i])
    print()

[[1 0]
 [0 1]]

[[1 0]
 [0 1]]

[[0 1 0]
 [0 0 1]
 [1 0 0]]

[[1]]

[[1 0]
 [0 1]]

[[1]]

[[1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]]

[[0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]]

[[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]



In [16]:
stemed_sentences[-1:]

['say someth dark coal use known dark coal emphas dark night']

## using the tensorflow

In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
vocab_size = 100

In [19]:

[ one_hot(sent , vocab_size) for sent in stemed_sentences ]

[[90, 58],
 [90, 46],
 [21, 13, 70],
 [73],
 [14, 20],
 [15],
 [14, 78, 21, 61],
 [93, 21, 12, 58, 5],
 [3, 17, 38, 58, 56, 57, 38, 58, 38, 38, 72]]