In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
import warnings
warnings.filterwarnings('ignore')

### Make own dataset

In [3]:
from sklearn.datasets import make_classification

In [4]:
X , y = make_classification(
    n_samples=1000,
    n_features=10,
    n_classes=2, # binary classification
    random_state=42
)

In [5]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]])

In [6]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

### train test split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train , X_test , y_train , y_test = train_test_split( X, y, test_size=0.25 , random_state=42 )

### Model selection

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
model = LogisticRegression()

In [11]:
model.fit( X_train , y_train )

LogisticRegression()

In [12]:
y_train_pred = model.predict( X_train )

y_test_pred = model.predict( X_test)

In [13]:
# probability of the both class and which ever is large that is predicted value
model.predict_proba( X_test )

array([[7.80402833e-01, 2.19597167e-01],
       [3.33949444e-02, 9.66605056e-01],
       [6.54296825e-01, 3.45703175e-01],
       [7.74596952e-02, 9.22540305e-01],
       [9.74932212e-01, 2.50677881e-02],
       [4.02885463e-02, 9.59711454e-01],
       [9.77941181e-01, 2.20588194e-02],
       [9.53536485e-01, 4.64635153e-02],
       [7.96205025e-01, 2.03794975e-01],
       [6.82676128e-01, 3.17323872e-01],
       [9.11092679e-01, 8.89073209e-02],
       [2.49227688e-01, 7.50772312e-01],
       [5.20867594e-01, 4.79132406e-01],
       [2.11303097e-01, 7.88696903e-01],
       [7.85887817e-01, 2.14112183e-01],
       [9.43614105e-01, 5.63858947e-02],
       [2.64777377e-02, 9.73522262e-01],
       [3.45014892e-01, 6.54985108e-01],
       [3.19886760e-01, 6.80113240e-01],
       [2.00611174e-01, 7.99388826e-01],
       [4.95911186e-01, 5.04088814e-01],
       [9.62345871e-01, 3.76541287e-02],
       [1.92455811e-01, 8.07544189e-01],
       [7.86728233e-01, 2.13271767e-01],
       [8.671754

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [15]:
print( "Training predictions" )

print(f'Accuracy of the traing data: { accuracy_score( y_train , y_train_pred ) }')

print(f'Confusion matrix of the traing data: { confusion_matrix( y_train , y_train_pred ) }')

Training predictions
Accuracy of the traing data: 0.8706666666666667
Confusion matrix of the traing data: [[342  46]
 [ 51 311]]


In [16]:
("Classfication Report of Training")

print(classification_report( y_train , y_train_pred ))

              precision    recall  f1-score   support

           0       0.87      0.88      0.88       388
           1       0.87      0.86      0.87       362

    accuracy                           0.87       750
   macro avg       0.87      0.87      0.87       750
weighted avg       0.87      0.87      0.87       750



In [17]:
print( "Testing predictions" )

print(f'Accuracy of the traing data: { accuracy_score( y_test , y_test_pred ) }')

print(f'Confusion matrix of the traing data: { confusion_matrix( y_test , y_test_pred ) }')

Testing predictions
Accuracy of the traing data: 0.84
Confusion matrix of the traing data: [[ 98  15]
 [ 25 112]]


In [18]:
("Classfication Report of test")

print(classification_report(y_test , y_test_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83       113
           1       0.88      0.82      0.85       137

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250



# Hyperparamter Tunning and cross validation

In [19]:
penalty = ['l1' , 'l2' , 'elasticnet']
c_values = [ 100 , 10, 1, 0.1 , 0.01]

solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

In [20]:
params = dict( penalty=penalty , C=c_values , solver=solver )

In [21]:
model = LogisticRegression(  )

### Grid searchCV

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold()

In [24]:
grid = GridSearchCV( estimator=model , param_grid=params , scoring='accuracy' ,cv=cv , n_jobs=-1 )

In [25]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [26]:
grid.fit( X_train , y_train )

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [27]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}

In [28]:
grid.best_score_

0.8773333333333333

In [29]:
y_pred = grid.predict( X_test )

In [30]:
print( "Testing predictions" )

print(f'Accuracy of the traing data: { accuracy_score( y_test , y_pred ) }')

print(f'Confusion matrix of the traing data: { confusion_matrix( y_test , y_pred ) }')

("Classfication Report of test")

print(classification_report(y_test , y_pred))

Testing predictions
Accuracy of the traing data: 0.84
Confusion matrix of the traing data: [[103  10]
 [ 30 107]]
              precision    recall  f1-score   support

           0       0.77      0.91      0.84       113
           1       0.91      0.78      0.84       137

    accuracy                           0.84       250
   macro avg       0.84      0.85      0.84       250
weighted avg       0.85      0.84      0.84       250



# Randomized Search Grid

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [32]:
model = LogisticRegression(  )

In [33]:
randomized = RandomizedSearchCV(
    estimator=model,
    param_distributions=params,
    cv=cv,
    scoring='accuracy'
)

In [34]:
randomized.fit(X_train , y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [35]:
randomized.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 1}

In [36]:
randomized.best_score_

0.8693333333333333

In [37]:
y_pred = randomized.predict( X_test )

In [38]:
print( "Testing predictions" )

print(f'Accuracy of the traing data: { accuracy_score( y_test , y_pred ) }')

print(f'Confusion matrix of the traing data: { confusion_matrix( y_test , y_pred ) }')

("Classfication Report of test")

print(classification_report(y_test , y_pred))

Testing predictions
Accuracy of the traing data: 0.84
Confusion matrix of the traing data: [[ 98  15]
 [ 25 112]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       113
           1       0.88      0.82      0.85       137

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250

